# Generated by Django 4.1.4 on 2023-12-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='livreur',
        ),
    ]
