# Generated by Django 4.1.4 on 2023-12-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandesApp', '0002_remove_commande_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='status',
        ),
    ]
