# Generated by Django 4.1.4 on 2023-12-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articlesApp', '0001_initial'),
        ('clientsApp', '0005_alter_client_adresse_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('En préparation', 'En préparation'), ('Livrée', 'Livrée')], default='En cours', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientsApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesApp.article')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraisonsApp.livraison')),
            ],
        ),
    ]
