# Generated by Django 4.1.4 on 2023-12-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0006_user_groups_user_is_superuser_user_last_login_and_more'),
        ('commandesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Fini', 'Fini')], default='En attente', max_length=20)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandesApp.commande')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.user')),
            ],
        ),
    ]
