# Generated by Django 4.1.4 on 2023-12-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonsApp', '0002_lignelivraison_ismodified_livraison_ismodified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignelivraison',
            name='isModified',
        ),
    ]
