# Generated by Django 4.1.4 on 2023-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisonsApp', '0005_alter_lignelivraison_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='status',
            field=models.CharField(choices=[('En préparation', 'En préparation'), ('En cours', 'En cours'), ('Livrée', 'Livrée')], default='En préparation', max_length=20),
        ),
    ]
