# Generated by Django 4.1.4 on 2023-12-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0010_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
