# Generated by Django 4.1.4 on 2023-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0011_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
