# Generated by Django 4.1.4 on 2023-12-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0012_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
