# Generated by Django 4.1.4 on 2023-12-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0014_remove_user_groups_remove_user_is_superuser_and_more'),
        ('itinerairesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.user'),
        ),
    ]
