# Generated by Django 4.1.4 on 2023-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0005_alter_client_adresse_complete'),
        ('itinerairesApp', '0002_alter_itineraire_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='commandes',
        ),
        migrations.AddField(
            model_name='itineraire',
            name='clients',
            field=models.ManyToManyField(blank=True, to='clientsApp.client'),
        ),
    ]
