# Generated by Django 4.1.4 on 2023-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandesApp', '0002_remove_commande_livreur'),
        ('itinerairesApp', '0002_remove_livraison_commande_livraison_commandes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='commandes',
            field=models.ManyToManyField(blank=True, to='commandesApp.commande'),
        ),
    ]
