# Generated by Django 4.1.4 on 2023-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandesApp', '0006_alter_lignecommande_quantite'),
        ('itinerairesApp', '0003_remove_itineraire_commandes_itineraire_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraire',
            name='commandes',
            field=models.ManyToManyField(blank=True, to='commandesApp.commande'),
        ),
    ]
