# Generated by Django 4.1.4 on 2023-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adresse',
        ),
        migrations.AddField(
            model_name='client',
            name='adresse_complete',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
    ]
