# Generated by Django 4.1.4 on 2023-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0002_remove_client_adresse_client_adresse_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
